name: test push

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: see secret?
      run: |
        export
        echo "VER:${{ steps.get_version.outputs.VERSION }}"

